controller_list:
  - name: right_arm_controller
    joints:
      - right_j0
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
  - name: head_controller
    joints:
      - right_j0
      - head_pan
